name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Cleaning up before running
      run: dotnet clean && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build OpenGL Version
      run: dotnet build --no-restore build/B3Engine.OpenGL.csproj
    - name: Build Base Version Testing
      run: dotnet build --no-restore test/Base
    - name: Build SDL Integration Testing
      run: dotnet build --no-restore test/SDL
    - name: Build GLSL Integration Testing
      run: dotnet build --no-restore test/GLSL
    - name: Test
      run: dotnet test --no-build --verbosity normal
